/*
 * Сервіс чатбота
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ua.gov.publicfinance.telegrambot.domain.model.dialogue.apiclient.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * EdrpouRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-11-10T13:37:39.038490800+02:00[Europe/Helsinki]")
public class EdrpouRequest {
  public static final String SERIALIZED_NAME_EDRPOUS = "edrpous";
  @SerializedName(SERIALIZED_NAME_EDRPOUS)
  private List<String> edrpous = null;


  public EdrpouRequest edrpous(List<String> edrpous) {
    
    this.edrpous = edrpous;
    return this;
  }

  public EdrpouRequest addEdrpousItem(String edrpousItem) {
    if (this.edrpous == null) {
      this.edrpous = new ArrayList<String>();
    }
    this.edrpous.add(edrpousItem);
    return this;
  }

   /**
   * Get edrpous
   * @return edrpous
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getEdrpous() {
    return edrpous;
  }


  public void setEdrpous(List<String> edrpous) {
    this.edrpous = edrpous;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EdrpouRequest edrpouRequest = (EdrpouRequest) o;
    return Objects.equals(this.edrpous, edrpouRequest.edrpous);
  }

  @Override
  public int hashCode() {
    return Objects.hash(edrpous);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EdrpouRequest {\n");
    sb.append("    edrpous: ").append(toIndentedString(edrpous)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

